POST http://localhost:9000/api/pagos HTTP/1.1
      Content-Type: application/json

      {
            "documento": 6543241,
            "fecha": "01-07-2020",
            "referencia": 354894,
            "valor": 325400
      }

# {
#      "nombre": "MANUEl DIAZ LARA",
#      "tipodoc": "Cedula",
#      "documento": 11234536,
#      "nacimiento": "01-12-1970",
#      "expedicion": "01-12-1990",
#      "ingresos": 4000000,
#      "egresos": 850324
#  }